language: c
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9']
      env:
        - COMPILER=gcc-4.9

    - os: linux
      compiler: clang
      env: COMPILER=clang
script:
  make CC=$COMPILER all
