language: c
sudo: false
os: linux
matrix:
    include:
        - compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - gcc-4.9
        env: CC=gcc-4.9
        - compiler: clang
script:
    - make all
